// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3EOrhrqQNBb6b13FTw6aCJjR9k9ACoF8',
    appId: '1:757827500353:web:2fe03d879dce45ffa609c0',
    messagingSenderId: '757827500353',
    projectId: 'bakeryapp-a6c40',
    authDomain: 'bakeryapp-a6c40.firebaseapp.com',
    storageBucket: 'bakeryapp-a6c40.appspot.com',
    measurementId: 'G-WD2L5P87PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5GOXPjOcQbbJvRXKzZ9j1TsaPpMDIyNk',
    appId: '1:757827500353:android:525691a718cd3acfa609c0',
    messagingSenderId: '757827500353',
    projectId: 'bakeryapp-a6c40',
    storageBucket: 'bakeryapp-a6c40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ib8Y-XINUzuQVh9awtieOsf3A_9iqjk',
    appId: '1:757827500353:ios:e42e3ecb585f8871a609c0',
    messagingSenderId: '757827500353',
    projectId: 'bakeryapp-a6c40',
    storageBucket: 'bakeryapp-a6c40.appspot.com',
    iosClientId: '757827500353-rmhbbbi04tq28mlooamfbcgj8mt9o19u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakeryOrderSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ib8Y-XINUzuQVh9awtieOsf3A_9iqjk',
    appId: '1:757827500353:ios:e42e3ecb585f8871a609c0',
    messagingSenderId: '757827500353',
    projectId: 'bakeryapp-a6c40',
    storageBucket: 'bakeryapp-a6c40.appspot.com',
    iosClientId: '757827500353-rmhbbbi04tq28mlooamfbcgj8mt9o19u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakeryOrderSystem',
  );
}
